/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Pings the database and reports the schema version. Answers 503 when the database is unreachable or a migration is dirty.
     */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register
     * @description Creates the account and the user's own organization, and sends a verification email. Login is refused until the email is verified. Passwords must be 12 to 72 bytes, use at least 5 different characters, not be a common password (including with digits or symbols added or letters swapped for digits) and not contain the user's name or email; failures return 400 `validation_failed` with the reason.
     */
    post: operations['register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/verify-email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify email */
    post: operations['verifyEmail'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/resend-verification': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Resend verification email
     * @description Emails a new verification link if the address belongs to an account that is not verified
     *     yet; earlier links stop working. The response is the same for unknown and already
     *     verified addresses, so it cannot be used to discover accounts. Limited to 3 requests per
     *     address and 10 per client IP per hour.
     */
    post: operations['resendVerification'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/forgot-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request a password reset
     * @description Emails a single-use link to `/reset-password?token=...` that expires in one hour, if the
     *     address belongs to an account; earlier reset links stop working. The response is the same
     *     for unknown addresses. Limited to 3 requests per address and 10 per client IP per hour.
     */
    post: operations['forgotPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/reset-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset password
     * @description Sets a new password with a reset token, marks the email verified, clears any login
     *     lockout and signs out every session. The new password must meet the password policy; a
     *     rejected password does not use up the token. Audited as `user.password_reset`.
     */
    post: operations['resetPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Log in
     * @description Returns an access token and a refresh token. With `use_cookie: true` (the web app) the
     *     refresh token is set as an `HttpOnly`, `SameSite=Strict` cookie (`__Host-dsm_refresh`, or
     *     `dsm_refresh` in development) and left out of the body, so page scripts cannot read it.
     */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh tokens
     * @description Exchanges a refresh token for a new access token and a new refresh token. The old refresh
     *     token is revoked. The token is read from the body, or from the refresh cookie when the body
     *     has none; a cookie is answered with a new cookie. A failed refresh does not change cookies.
     */
    post: operations['refreshTokens'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Log out
     * @description Revokes the refresh token from the body, or from the refresh cookie, and clears the cookie.
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current user */
    get: operations['getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change password
     * @description Sets a new password and signs out every other session of the user by revoking their
     *     refresh tokens; the session making the request stays signed in. Access tokens already
     *     issued to other sessions stay valid until they expire (at most 15 minutes). Audited as
     *     `user.password_changed` with the number of sessions ended.
     */
    post: operations['changePassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List sessions
     * @description The caller's active sessions: logins whose refresh token is still valid, most recently
     *     used first. `current` marks the session the access token belongs to.
     */
    get: operations['listSessions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sessions/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Sign out a session
     * @description Revokes the session's refresh token, so it cannot get new access tokens (an access token
     *     it already holds stays valid for at most 15 minutes). Revoking the current session also
     *     clears the refresh cookie. Audited as `user.sessions_revoked`.
     */
    delete: operations['revokeSession'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sessions/revoke-others': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sign out everywhere else
     * @description Revokes every session of the caller except the current one. Audited as `user.sessions_revoked`.
     */
    post: operations['revokeOtherSessions'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/orgs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List organizations
     * @description Organizations the caller belongs to, with their role, ordered by name.
     */
    get: operations['listOrganizations'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/orgs/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['OrganizationIdPath'];
      };
      cookie?: never;
    };
    /** Get organization */
    get: operations['getOrganization'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Rename organization
     * @description Requires the owner or admin role in the organization.
     */
    patch: operations['updateOrganization'];
    trace?: never;
  };
  '/orgs/{id}/members': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['OrganizationIdPath'];
      };
      cookie?: never;
    };
    /**
     * List organization members
     * @description Any member can see who else is in the organization.
     */
    get: operations['listOrganizationMembers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/orgs/{id}/members/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['OrganizationIdPath'];
        userId: string;
      };
      cookie?: never;
    };
    get?: never;
    /**
     * Change organization role
     * @description Requires owner or admin. Only owners can grant or change the owner role, and the last owner cannot be demoted.
     */
    put: operations['updateOrganizationMember'];
    post?: never;
    /**
     * Remove organization member
     * @description Requires owner or admin. Also removes the person from every vault in the organization. Callers cannot remove themselves, only owners can remove an owner, and the last owner stays.
     */
    delete: operations['removeOrganizationMember'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/orgs/{id}/invites': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['OrganizationIdPath'];
      };
      cookie?: never;
    };
    /**
     * List open invitations
     * @description Invitations not yet accepted, revoked or expired. Requires owner or admin.
     */
    get: operations['listInvites'];
    put?: never;
    /**
     * Invite by email
     * @description Requires owner or admin; only owners can invite another owner. Emails a single-use link
     *     that expires in 7 days (logged instead in development without SMTP). Inviting the same
     *     address again replaces the earlier link. `email_sent` is false when the invitation was
     *     stored but could not be delivered.
     */
    post: operations['createInvite'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/orgs/{id}/invites/{inviteId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['OrganizationIdPath'];
        inviteId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Revoke invitation
     * @description Requires owner or admin. The link stops working.
     */
    delete: operations['revokeInvite'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/invites/lookup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Look up an invitation
     * @description Describes an open invitation for the accept page. The token is sent in the body so it never appears in URLs or access logs. No authentication.
     */
    post: operations['lookupInvite'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/invites/accept': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Accept an invitation
     * @description Adds the logged-in user to the organization. The account's email must match the invitation. New users accept by registering with `invite_token` instead.
     */
    post: operations['acceptInvite'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List vaults
     * @description Vaults the caller is a member of, plus every vault in organizations they own or administer. Newest first.
     */
    get: operations['listVaults'];
    put?: never;
    /**
     * Create vault
     * @description Requires the owner, admin or developer role in the organization. The creator becomes the vault's owner. Without `organization_id` the caller's first organization is used.
     */
    post: operations['createVault'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
      };
      cookie?: never;
    };
    /**
     * Get vault
     * @description Requires read permission.
     */
    get: operations['getVault'];
    /**
     * Update vault
     * @description Requires write permission.
     */
    put: operations['updateVault'];
    post?: never;
    /**
     * Delete vault
     * @description Requires delete permission (owners only). The vault is soft-deleted.
     */
    delete: operations['deleteVault'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults/{id}/rotate-key': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rotate the vault's data key
     * @description Generates a new data key for the vault and re-encrypts every secret value under it in one
     *     transaction; the old key is discarded. Use it after a suspected exposure of the vault's
     *     data. Requires the manage-members permission (owners and admins). Audited as
     *     `vault.key_rotated`.
     */
    post: operations['rotateVaultKey'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults/{vault_id}/envs': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        vault_id: string;
      };
      cookie?: never;
    };
    /**
     * List environments
     * @description Requires read permission. Newest first.
     */
    get: operations['listEnvironments'];
    put?: never;
    /**
     * Create environment
     * @description Requires write permission.
     */
    post: operations['createEnvironment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/envs/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    /**
     * Get environment
     * @description Requires read permission on the environment's vault.
     */
    get: operations['getEnvironment'];
    /**
     * Update environment
     * @description Requires write permission.
     */
    put: operations['updateEnvironment'];
    post?: never;
    /**
     * Delete environment
     * @description Requires write permission. The environment is soft-deleted.
     */
    delete: operations['deleteEnvironment'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/envs/{id}/secrets': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    /**
     * List secrets
     * @description Returns metadata only, never values. Requires read permission.
     */
    get: operations['listSecrets'];
    put?: never;
    /**
     * Create secret
     * @description Requires write permission. The value is encrypted with the vault's data key.
     */
    post: operations['createSecret'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/envs/{id}/export': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Export environment values
     * @description Decrypts every value in the environment, for downloading as a `.env` file. Requires reveal
     *     permission. Audited once as `env.exported` with the key names.
     */
    post: operations['exportEnvironment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/envs/{id}/import': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Import values
     * @description Creates keys that do not exist. With `overwrite`, existing keys get the new value unless it
     *     is the same (no new version is added then); otherwise they are skipped. With `dry_run`
     *     nothing is written and the response is a preview. Requires write permission. Each key is
     *     written separately and audited as usual, and a real import adds one `env.imported` event;
     *     if a write fails part-way, the keys before it stay imported.
     */
    post: operations['importEnvironment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/envs/{id}/copy-from': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Copy values from another environment
     * @description Copies the named keys (or all of them) from another environment of the same vault, using
     *     the same rules as an import: missing keys are created, existing ones are updated only with
     *     `overwrite`, and identical values are left alone. Requires write permission on the vault
     *     and reveal permission, because the source values are decrypted; the read is audited on the
     *     source as `env.exported` and the write as `env.imported`.
     */
    post: operations['copySecrets'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/envs/{id}/tokens': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    /**
     * List service tokens
     * @description Active tokens for the environment (never their values). Requires manage-members permission on the vault.
     */
    get: operations['listServiceTokens'];
    put?: never;
    /**
     * Create a service token
     * @description Issues a read-only token for this environment. The `token` value is returned only in this response; the API stores a SHA-256 hash. Requires manage-members permission on the vault.
     */
    post: operations['createServiceToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tokens/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke a service token */
    delete: operations['revokeServiceToken'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/token/secrets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read secrets with a service token
     * @description Returns every secret in the token's environment. Authenticate with `Authorization Bearer dsm_st_...`. Each call is audited as `env.exported` by `token:<name>`. Responses are marked `Cache-Control no-store`.
     */
    get: operations['readTokenSecrets'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/secrets/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['SecretIdPath'];
      };
      cookie?: never;
    };
    get?: never;
    /**
     * Update secret
     * @description Requires write permission. Omit `value` to keep the stored value and change only metadata; description, rotation interval, expiry and metadata are replaced by the values sent.
     */
    put: operations['updateSecret'];
    post?: never;
    /**
     * Delete secret
     * @description Requires write permission. The secret is soft-deleted.
     */
    delete: operations['deleteSecret'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/secrets/{id}/reveal': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['SecretIdPath'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reveal secret value
     * @description Requires reveal permission (owner, admin or on-call). Every reveal is recorded in the audit log.
     */
    post: operations['revealSecret'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/secrets/{id}/versions': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['SecretIdPath'];
      };
      cookie?: never;
    };
    /**
     * List secret versions
     * @description Every value the secret has had, newest first, without the values. A new version is added
     *     each time the value changes or an earlier version is restored. Requires read permission.
     */
    get: operations['listSecretVersions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/secrets/{id}/versions/{version}/reveal': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['SecretIdPath'];
        version: components['parameters']['VersionPath'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reveal an earlier value
     * @description Requires reveal permission. Audited as `secret.revealed` with the version number.
     */
    post: operations['revealSecretVersion'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/secrets/{id}/versions/{version}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['SecretIdPath'];
        version: components['parameters']['VersionPath'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Roll back to an earlier value
     * @description Makes the value of an earlier version current again by adding it as a new version, so
     *     history is never rewritten. Requires write permission. Audited as `secret.restored`.
     */
    post: operations['restoreSecretVersion'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults/{id}/members': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
      };
      cookie?: never;
    };
    /**
     * List members
     * @description Explicit vault members. Requires read permission.
     */
    get: operations['listMembers'];
    put?: never;
    /**
     * Add member
     * @description Requires manage-members permission. The user must already belong to the vault's organization. Only owners can add another owner.
     */
    post: operations['addMember'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults/{id}/members/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
        userId: string;
      };
      cookie?: never;
    };
    get?: never;
    /**
     * Change member role
     * @description Requires manage-members permission. Only owners can grant or change the owner role, and the last owner cannot be demoted.
     */
    put: operations['updateMember'];
    post?: never;
    /**
     * Remove member
     * @description Requires manage-members permission. Callers cannot remove themselves, only owners can remove an owner, and the last owner cannot be removed.
     */
    delete: operations['removeMember'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/audit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Query the audit log
     * @description Newest first. Callers see their own events, every event in organizations they own or
     *     administer, and events in vaults where they are an owner or admin. snake_case aliases
     *     (`vault_id`, `user_id`, `org_id`, `environment_id`, `start_time`, `end_time`) are also accepted.
     */
    get: operations['listAuditEvents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Dashboard statistics
     * @description Counts across the vaults the caller can access.
     */
    get: operations['getStats'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/alerts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Dashboard alerts
     * @description Expired and soon-expiring (7 days) secrets and overdue rotations in accessible vaults, and members without a login in 90 days in vaults the caller manages. Ordered by severity, at most 50.
     */
    get: operations['listAlerts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      /**
       * @description Machine-readable code, e.g. not_found, forbidden, invalid_request
       * @example not_found
       */
      error: string;
      /** @example Vault not found */
      message: string;
    };
    MessageResponse: {
      message: string;
    };
    /** @enum {string} */
    Role: 'owner' | 'admin' | 'developer' | 'oncall' | 'viewer';
    RegisterRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
      name: string;
      /** @description Joins the invited organization instead of creating a personal one; the email must match the invitation and no verification is needed */
      invite_token?: string;
    };
    RegisterResponse: {
      /** Format: uuid */
      user_id: string;
      message: string;
      /** @description False when an invitation was accepted and the account can log in straight away */
      verification_required: boolean;
    };
    VerifyEmailRequest: {
      token: string;
    };
    EmailRequest: {
      /** Format: email */
      email: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
      /** @description Set the refresh token as an HttpOnly cookie instead of returning it (default false) */
      use_cookie?: boolean;
    };
    RefreshRequest: {
      /** @description Omit to use the refresh cookie */
      refresh_token?: string;
      /** @description Return the new refresh token as a cookie even though one was sent in the body (default false) */
      use_cookie?: boolean;
    };
    LogoutRequest: {
      /** @description Omit to use the refresh cookie */
      refresh_token?: string;
    };
    AuthTokens: {
      access_token: string;
      /** @description Absent when the refresh token was set as a cookie */
      refresh_token?: string;
      /** @description Access token lifetime in seconds */
      expires_in: number;
    };
    Session: {
      /** Format: uuid */
      id: string;
      /**
       * Format: date-time
       * @description When the user logged in
       */
      created_at: string;
      /**
       * Format: date-time
       * @description Last login or token refresh
       */
      last_used_at: string;
      /**
       * Format: date-time
       * @description When the session ends unless refreshed
       */
      expires_at: string;
      ip_address: string | null;
      user_agent: string | null;
      current: boolean;
    };
    ChangePasswordRequest: {
      /** Format: password */
      current_password: string;
      /** Format: password */
      new_password: string;
    };
    UserOrganization: {
      /** Format: uuid */
      id: string;
      name: string;
      role: components['schemas']['Role'];
    };
    UserProfile: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      name: string;
      /** Format: date-time */
      created_at: string;
      organizations: components['schemas']['UserOrganization'][];
    };
    Organization: {
      /** Format: uuid */
      id: string;
      name: string;
      role: components['schemas']['Role'];
      member_count: number;
      vault_count: number;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    Invite: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      organization_id: string;
      organization_name: string;
      /** Format: email */
      email: string;
      role: components['schemas']['Role'];
      invited_by: string;
      /** Format: uuid */
      invited_by_id: string | null;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      expires_at: string;
    };
    CreateInviteResponse: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      organization_id: string;
      organization_name: string;
      /** Format: email */
      email: string;
      role: components['schemas']['Role'];
      invited_by: string;
      /** Format: uuid */
      invited_by_id: string | null;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      expires_at: string;
      email_sent: boolean;
    };
    CreateInviteRequest: {
      /** Format: email */
      email: string;
      role: components['schemas']['Role'];
    };
    InviteTokenRequest: {
      token: string;
    };
    InviteLookup: {
      organization_name: string;
      /** Format: email */
      email: string;
      role: components['schemas']['Role'];
      invited_by: string;
      /** Format: date-time */
      expires_at: string;
      /** @description Whether an account with the invited address exists (log in to accept) or not (register) */
      account_exists: boolean;
    };
    UpdateOrganizationRequest: {
      name: string;
    };
    OrganizationMember: {
      /** Format: uuid */
      user_id: string;
      /** Format: email */
      email: string;
      name: string;
      role: components['schemas']['Role'];
      /** Format: date-time */
      joined_at: string;
      /** Format: date-time */
      last_login_at: string | null;
    };
    Vault: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      organization_id: string;
      organization_name: string;
      name: string;
      description: string | null;
      user_role: components['schemas']['Role'];
      secret_count: number;
      env_count: number;
      /** Format: uuid */
      created_by_id: string | null;
      /** @description Creator's display name; empty when unknown */
      created_by: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    VaultKeyRotation: {
      /** Format: uuid */
      vault_id: string;
      /** @description Secret values re-encrypted, including deleted secrets */
      secrets_reencrypted: number;
      /** Format: date-time */
      rotated_at: string;
    };
    CreateVaultRequest: {
      name: string;
      description?: string | null;
      /** Format: uuid */
      organization_id?: string;
    };
    UpdateVaultRequest: {
      name: string;
      description?: string | null;
    };
    Environment: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      vault_id: string;
      name: string;
      description: string | null;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** @description Live secrets; only filled in by the list endpoint */
      secret_count: number;
    };
    EnvironmentRequest: {
      /** @example staging */
      name: string;
      description?: string | null;
    };
    RotationPolicy: {
      interval_days: number;
      /**
       * Format: date-time
       * @description When the value last changed; null if never since creation
       */
      last_rotated_at: string | null;
      /**
       * Format: date-time
       * @description One interval after the last rotation, or after creation
       */
      next_rotation_at: string;
    };
    SecretMetadata: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      environment_id: string;
      key_name: string;
      description?: string;
      rotation_interval_days?: number;
      /** Format: date-time */
      expires_at?: string;
      /** Format: date-time */
      last_rotated_at?: string;
      metadata?: {
        [key: string]: unknown;
      };
      /** Format: uuid */
      created_by: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: date-time */
      last_updated_at: string;
      /** Format: uuid */
      last_updated_by_id: string | null;
      /** @description Display name of the last editor */
      last_updated_by: string;
      rotation_policy: components['schemas']['RotationPolicy'] | null;
      /** @description Number of the current value; it increases each time the value changes */
      version: number;
    };
    ExportedSecret: {
      key: string;
      value: string;
      /** Format: date-time */
      expires_at: string | null;
    };
    ImportResult: {
      created: string[];
      updated: string[];
      /** @description Existing keys that already have the imported value */
      unchanged: string[];
      /** @description Existing keys left alone because overwrite was off */
      skipped: string[];
      dry_run: boolean;
    };
    SecretVersion: {
      version: number;
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      created_by_id: string | null;
      /** @description Display name of whoever set this value; empty when unknown */
      created_by: string;
      /** @description The earlier version this one was restored from */
      restored_from: number | null;
      current: boolean;
    };
    CreateSecretRequest: {
      key_name: string;
      /**
       * Format: password
       * @description At most 64 KiB
       */
      value: string;
      description?: string | null;
      rotation_interval_days?: number | null;
      /** Format: date-time */
      expires_at?: string | null;
      /** @description Up to 50 labels; keys up to 100 characters, string values up to 500 */
      metadata?: {
        [key: string]: string;
      } | null;
    };
    UpdateSecretRequest: {
      /**
       * Format: password
       * @description New value; omit to keep the current one
       */
      value?: string;
      description?: string | null;
      rotation_interval_days?: number | null;
      /** Format: date-time */
      expires_at?: string | null;
      metadata?: {
        [key: string]: unknown;
      } | null;
    };
    SecretReveal: {
      /** Format: uuid */
      id: string;
      key_name: string;
      value: string;
      /** @description Seconds clients should show the value before hiding it */
      expires_in: number;
    };
    MemberPermissions: {
      can_read: boolean;
      can_write: boolean;
      can_reveal: boolean;
      can_manage_members: boolean;
      can_delete: boolean;
    };
    Member: {
      /** Format: uuid */
      user_id: string;
      /** Format: email */
      email: string;
      name: string;
      role: components['schemas']['Role'];
      permissions: components['schemas']['MemberPermissions'];
      /** Format: date-time */
      added_at: string;
      /** @description Display name of whoever added the member; empty when unknown */
      added_by: string;
      /** Format: uuid */
      added_by_id: string | null;
    };
    AddMemberRequest: {
      /** Format: email */
      email: string;
      role: components['schemas']['Role'];
    };
    UpdateMemberRequest: {
      role: components['schemas']['Role'];
    };
    ServiceToken: {
      /** Format: uuid */
      id: string;
      name: string;
      /** @description The first characters of the token, to recognise it */
      prefix: string;
      /** Format: uuid */
      environment_id: string;
      environment_name: string;
      /** Format: uuid */
      vault_id: string;
      vault_name: string;
      created_by: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      expires_at: string | null;
      /** Format: date-time */
      last_used_at: string | null;
    };
    CreatedServiceToken: {
      /** Format: uuid */
      id: string;
      name: string;
      prefix: string;
      /** Format: uuid */
      environment_id: string;
      environment_name: string;
      /** Format: uuid */
      vault_id: string;
      vault_name: string;
      created_by: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      expires_at: string | null;
      /** Format: date-time */
      last_used_at: string | null;
      /** @description The token itself. Shown only once. */
      token: string;
    };
    CreateServiceTokenRequest: {
      name: string;
      expires_in_days?: number | null;
    };
    TokenSecrets: {
      vault_name: string;
      environment_name: string;
      token_name: string;
      secrets: {
        key: string;
        value: string;
        /**
         * Format: date-time
         * @description When the value expires; expired values are still returned so callers can warn
         */
        expires_at: string | null;
      }[];
    };
    /** @enum {string} */
    AuditAction:
      | 'login.success'
      | 'login.failure'
      | 'login.locked'
      | 'secret.created'
      | 'secret.updated'
      | 'secret.deleted'
      | 'secret.revealed'
      | 'member.added'
      | 'member.removed'
      | 'member.role_changed'
      | 'vault.created'
      | 'vault.updated'
      | 'vault.deleted'
      | 'vault.key_rotated'
      | 'env.created'
      | 'env.updated'
      | 'env.deleted'
      | 'org.updated'
      | 'org.member_role_changed'
      | 'org.member_removed'
      | 'invite.created'
      | 'invite.revoked'
      | 'invite.accepted'
      | 'token.created'
      | 'token.revoked'
      | 'env.exported'
      | 'user.password_changed'
      | 'user.sessions_revoked'
      | 'user.password_reset'
      | 'secret.restored'
      | 'env.imported';
    AuditEvent: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      timestamp: string;
      action: components['schemas']['AuditAction'];
      /**
       * Format: uuid
       * @description Null when a service token acted
       */
      user_id: string | null;
      /** @description The actor's email, or token:<name> for a service token */
      user_email: string;
      /** Format: uuid */
      service_token_id: string | null;
      /** Format: uuid */
      organization_id: string | null;
      /** Format: uuid */
      vault_id: string | null;
      vault_name: string | null;
      /** Format: uuid */
      environment_id: string | null;
      environment_name: string | null;
      /** @description secret, environment, vault, member, organization, invite, service_token or user */
      target_type: string;
      /** Format: uuid */
      target_id: string | null;
      target_name: string | null;
      ip_address: string | null;
      user_agent: string | null;
      metadata: {
        [key: string]: unknown;
      };
    };
    AuditEventPage: {
      data: components['schemas']['AuditEvent'][];
      total: number;
      page: number;
      limit: number;
      has_more: boolean;
    };
    DashboardStats: {
      vaults: number;
      environments: number;
      secrets: number;
      secrets_expired: number;
      secrets_expiring_soon: number;
      secrets_rotation_overdue: number;
      /** @description People with access to the caller's vaults */
      users: number;
      /** @description Of those, how many logged in within active_window_days */
      active_users: number;
      expiring_soon_days: number;
      active_window_days: number;
    };
    DashboardAlert: {
      /** @enum {string} */
      type: 'secret_expired' | 'secret_expiring' | 'rotation_overdue' | 'member_inactive';
      /** @enum {string} */
      severity: 'high' | 'medium' | 'low';
      message: string;
      /** Format: uuid */
      vault_id: string;
      vault_name: string;
      environment_name: string | null;
      target_id: string;
      target_name: string;
      /**
       * Format: date-time
       * @description Expiry or rotation due date, or the member's last login (null if never)
       */
      due_at: string | null;
    };
    Health: {
      /** @enum {string} */
      status: 'ok' | 'unavailable';
      /** @example ok */
      database: string;
      migration_version: number | null;
      migration_dirty: boolean;
      /** Format: date-time */
      started_at: string;
      uptime_seconds: number;
      version: string;
      /** Format: date-time */
      timestamp: string;
    };
  };
  responses: {
    /** @description Unexpected server error (`internal_error`); details are logged, never returned */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Rate limit exceeded (`rate_limited`), or for login an account temporarily locked after repeated failures (`account_locked`); retry after the number of seconds in Retry-After */
    TooManyRequests: {
      headers: {
        'Retry-After'?: number;
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Request body larger than 1 MiB (`body_too_large`) */
    PayloadTooLarge: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Invalid ID, query parameter or body (`invalid_request`), or a field breaking the input rules (`validation_failed`) */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Missing, invalid or expired access token */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description The caller's role does not allow this action (`forbidden`) */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Not found, or the caller has no access to it (`not_found`) */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description A resource with that name already exists (`duplicate` or `conflict`) */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: {
    OrganizationIdPath: string;
    VaultIdPath: string;
    EnvironmentIdPath: string;
    VersionPath: number;
    SecretIdPath: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Healthy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
      500: components['responses']['InternalError'];
      /** @description Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest'];
      };
    };
    responses: {
      /** @description Registered */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RegisterResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      /** @description An account with this email already exists (`user_already_exists`) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      413: components['responses']['PayloadTooLarge'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalError'];
    };
  };
  verifyEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyEmailRequest'];
      };
    };
    responses: {
      /** @description Verified */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'];
        };
      };
      /** @description Missing, invalid, used or expired token (`invalid_verification`) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      413: components['responses']['PayloadTooLarge'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalError'];
    };
  };
  resendVerification: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailRequest'];
      };
    };
    responses: {
      /** @description Accepted; an email is sent only if the account needs verifying */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      413: components['responses']['PayloadTooLarge'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalError'];
    };
  };
  forgotPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailRequest'];
      };
    };
    responses: {
      /** @description Accepted; an email is sent only if the account exists */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      413: components['responses']['PayloadTooLarge'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalError'];
    };
  };
  resetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          token: string;
          /** Format: password */
          new_password: string;
        };
      };
    };
    responses: {
      /** @description Password reset */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'];
        };
      };
      /** @description Missing fields, a password that fails the policy (`validation_failed`), or an invalid, expired or used token (`invalid_reset_token`) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      413: components['responses']['PayloadTooLarge'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalError'];
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Logged in */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthTokens'];
        };
      };
      400: components['responses']['BadRequest'];
      /** @description Wrong email or password (`invalid_credentials`) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Email not verified yet (`email_not_verified`) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      413: components['responses']['PayloadTooLarge'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalError'];
    };
  };
  refreshTokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshRequest'];
      };
    };
    responses: {
      /** @description New tokens */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthTokens'];
        };
      };
      400: components['responses']['BadRequest'];
      /** @description Invalid, expired or revoked refresh token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      413: components['responses']['PayloadTooLarge'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalError'];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LogoutRequest'];
      };
    };
    responses: {
      /** @description Logged out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      /** @description Unknown refresh token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      413: components['responses']['PayloadTooLarge'];
      500: components['responses']['InternalError'];
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The authenticated user and their organizations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserProfile'];
        };
      };
      401: components['responses']['Unauthorized'];
      500: components['responses']['InternalError'];
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest'];
      };
    };
    responses: {
      /** @description Password changed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'];
        };
      };
      /** @description Missing fields, a new password that fails the password policy (`validation_failed`), or wrong current password */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      401: components['responses']['Unauthorized'];
      413: components['responses']['PayloadTooLarge'];
      500: components['responses']['InternalError'];
    };
  };
  listSessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Sessions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Session'][];
        };
      };
      401: components['responses']['Unauthorized'];
      500: components['responses']['InternalError'];
    };
  };
  revokeSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Signed out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  revokeOtherSessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Sessions signed out */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            sessions_revoked: number;
          };
        };
      };
      401: components['responses']['Unauthorized'];
      500: components['responses']['InternalError'];
    };
  };
  listOrganizations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Organizations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Organization'][];
        };
      };
      401: components['responses']['Unauthorized'];
      500: components['responses']['InternalError'];
    };
  };
  getOrganization: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['OrganizationIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Organization */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Organization'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  updateOrganization: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['OrganizationIdPath'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateOrganizationRequest'];
      };
    };
    responses: {
      /** @description Renamed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Organization'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      413: components['responses']['PayloadTooLarge'];
      500: components['responses']['InternalError'];
    };
  };
  listOrganizationMembers: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['OrganizationIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Members */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrganizationMember'][];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  updateOrganizationMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['OrganizationIdPath'];
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateMemberRequest'];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrganizationMember'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      413: components['responses']['PayloadTooLarge'];
      500: components['responses']['InternalError'];
    };
  };
  removeOrganizationMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['OrganizationIdPath'];
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  listInvites: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['OrganizationIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Invitations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Invite'][];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  createInvite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['OrganizationIdPath'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateInviteRequest'];
      };
    };
    responses: {
      /** @description Invitation created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CreateInviteResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      /** @description The person is already a member (`already_member`) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      413: components['responses']['PayloadTooLarge'];
      500: components['responses']['InternalError'];
    };
  };
  revokeInvite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['OrganizationIdPath'];
        inviteId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  lookupInvite: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InviteTokenRequest'];
      };
    };
    responses: {
      /** @description Invitation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InviteLookup'];
        };
      };
      400: components['responses']['BadRequest'];
      /** @description Unknown, expired, revoked or used invitation (`invalid_invite`) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      413: components['responses']['PayloadTooLarge'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalError'];
    };
  };
  acceptInvite: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InviteTokenRequest'];
      };
    };
    responses: {
      /** @description Joined */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Organization'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      /** @description The invitation is for another address (`invite_email_mismatch`) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Unknown, expired, revoked or used invitation (`invalid_invite`) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Already a member (`already_member`) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      413: components['responses']['PayloadTooLarge'];
      500: components['responses']['InternalError'];
    };
  };
  listVaults: {
    parameters: {
      query?: {
        /** @description Only include this organization (snake_case `organization_id` is also accepted) */
        organizationId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Vaults */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Vault'][];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      500: components['responses']['InternalError'];
    };
  };
  createVault: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateVaultRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Vault'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      409: components['responses']['Conflict'];
      413: components['responses']['PayloadTooLarge'];
      500: components['responses']['InternalError'];
    };
  };
  getVault: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Vault */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Vault'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  updateVault: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateVaultRequest'];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Vault'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      413: components['responses']['PayloadTooLarge'];
      500: components['responses']['InternalError'];
    };
  };
  deleteVault: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  rotateVaultKey: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Rotated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VaultKeyRotation'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  listEnvironments: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        vault_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Environments */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Environment'][];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  createEnvironment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        vault_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EnvironmentRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Environment'];
        };
      };
      /** @description Invalid body or name (`invalid_name`) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      413: components['responses']['PayloadTooLarge'];
      500: components['responses']['InternalError'];
    };
  };
  getEnvironment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Environment */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Environment'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  updateEnvironment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EnvironmentRequest'];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Environment'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      413: components['responses']['PayloadTooLarge'];
      500: components['responses']['InternalError'];
    };
  };
  deleteEnvironment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  listSecrets: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Secrets */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SecretMetadata'][];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  createSecret: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSecretRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SecretMetadata'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      413: components['responses']['PayloadTooLarge'];
      500: components['responses']['InternalError'];
    };
  };
  exportEnvironment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Decrypted values */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            secrets: components['schemas']['ExportedSecret'][];
          };
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalError'];
    };
  };
  importEnvironment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          secrets: {
            key: string;
            /** Format: password */
            value: string;
          }[];
          /** @description Update existing keys (default false) */
          overwrite?: boolean;
          /** @description Only report what would happen (default false) */
          dry_run?: boolean;
        };
      };
    };
    responses: {
      /** @description What was (or would be) done with each key */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImportResult'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      413: components['responses']['PayloadTooLarge'];
      500: components['responses']['InternalError'];
    };
  };
  copySecrets: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: uuid */
          source_environment_id: string;
          /** @description Keys to copy; omit or leave empty to copy them all */
          keys?: string[];
          overwrite?: boolean;
          dry_run?: boolean;
        };
      };
    };
    responses: {
      /** @description What was (or would be) done with each key */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImportResult'];
        };
      };
      /** @description Missing source, the same environment, a different vault, or no matching keys (`validation_failed`) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      413: components['responses']['PayloadTooLarge'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalError'];
    };
  };
  listServiceTokens: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tokens */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ServiceToken'][];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  createServiceToken: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateServiceTokenRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CreatedServiceToken'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      413: components['responses']['PayloadTooLarge'];
      500: components['responses']['InternalError'];
    };
  };
  revokeServiceToken: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  readTokenSecrets: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Secrets */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenSecrets'];
        };
      };
      401: components['responses']['Unauthorized'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalError'];
    };
  };
  updateSecret: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['SecretIdPath'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateSecretRequest'];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SecretMetadata'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      413: components['responses']['PayloadTooLarge'];
      500: components['responses']['InternalError'];
    };
  };
  deleteSecret: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['SecretIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  revealSecret: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['SecretIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Decrypted value */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SecretReveal'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalError'];
    };
  };
  listSecretVersions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['SecretIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Versions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SecretVersion'][];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  revealSecretVersion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['SecretIdPath'];
        version: components['parameters']['VersionPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Decrypted value of that version */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SecretReveal'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      429: components['responses']['TooManyRequests'];
      500: components['responses']['InternalError'];
    };
  };
  restoreSecretVersion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['SecretIdPath'];
        version: components['parameters']['VersionPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The secret with its new current version */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SecretMetadata'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      /** @description The version is already current (`version_is_current`) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  listMembers: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Members */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Member'][];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  addMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddMemberRequest'];
      };
    };
    responses: {
      /** @description Added */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Member'];
        };
      };
      /** @description Invalid role or the user is not in the organization */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      /** @description Vault not found, or no user with that email */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      409: components['responses']['Conflict'];
      413: components['responses']['PayloadTooLarge'];
      500: components['responses']['InternalError'];
    };
  };
  updateMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateMemberRequest'];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Member'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      413: components['responses']['PayloadTooLarge'];
      500: components['responses']['InternalError'];
    };
  };
  removeMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  listAuditEvents: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        organizationId?: string;
        vaultId?: string;
        environmentId?: string;
        userId?: string;
        /** @description Case-insensitive substring of the actor's email */
        userEmail?: string;
        action?: components['schemas']['AuditAction'];
        /** @description Leave out events with this action; repeat for several */
        excludeAction?: components['schemas']['AuditAction'][];
        /** @description Inclusive; RFC 3339 timestamp or YYYY-MM-DD (UTC midnight) */
        startDate?: string;
        /** @description Exclusive for timestamps; a YYYY-MM-DD day includes that whole day */
        endDate?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description One page of events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuditEventPage'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      500: components['responses']['InternalError'];
    };
  };
  getStats: {
    parameters: {
      query?: {
        /** @description Only include this organization (snake_case `organization_id` is also accepted) */
        organizationId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Statistics */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DashboardStats'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      500: components['responses']['InternalError'];
    };
  };
  listAlerts: {
    parameters: {
      query?: {
        /** @description Only include this organization (snake_case `organization_id` is also accepted) */
        organizationId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Alerts */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DashboardAlert'][];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      500: components['responses']['InternalError'];
    };
  };
}
