/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Pings the database and reports the schema version. Answers 503 when the database is unreachable or a migration is dirty.
     */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register
     * @description Creates the account and the user's own organization, and sends a verification email. Login is refused until the email is verified.
     */
    post: operations['register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/verify-email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify email */
    post: operations['verifyEmail'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Log in */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh tokens
     * @description Exchanges a refresh token for a new access token and a new refresh token. The old refresh token is revoked.
     */
    post: operations['refreshTokens'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Log out
     * @description Revokes the refresh token.
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current user */
    get: operations['getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Change password */
    post: operations['changePassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List vaults
     * @description Vaults the caller is a member of, plus every vault in organizations they own or administer. Newest first.
     */
    get: operations['listVaults'];
    put?: never;
    /**
     * Create vault
     * @description Requires the owner, admin or developer role in the organization. The creator becomes the vault's owner. Without `organization_id` the caller's first organization is used.
     */
    post: operations['createVault'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
      };
      cookie?: never;
    };
    /**
     * Get vault
     * @description Requires read permission.
     */
    get: operations['getVault'];
    /**
     * Update vault
     * @description Requires write permission.
     */
    put: operations['updateVault'];
    post?: never;
    /**
     * Delete vault
     * @description Requires delete permission (owners only). The vault is soft-deleted.
     */
    delete: operations['deleteVault'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults/{vault_id}/envs': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        vault_id: string;
      };
      cookie?: never;
    };
    /**
     * List environments
     * @description Requires read permission. Newest first.
     */
    get: operations['listEnvironments'];
    put?: never;
    /**
     * Create environment
     * @description Requires write permission.
     */
    post: operations['createEnvironment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/envs/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    /**
     * Get environment
     * @description Requires read permission on the environment's vault.
     */
    get: operations['getEnvironment'];
    /**
     * Update environment
     * @description Requires write permission.
     */
    put: operations['updateEnvironment'];
    post?: never;
    /**
     * Delete environment
     * @description Requires write permission. The environment is soft-deleted.
     */
    delete: operations['deleteEnvironment'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/envs/{id}/secrets': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    /**
     * List secrets
     * @description Returns metadata only, never values. Requires read permission.
     */
    get: operations['listSecrets'];
    put?: never;
    /**
     * Create secret
     * @description Requires write permission. The value is encrypted with the vault's data key.
     */
    post: operations['createSecret'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/secrets/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['SecretIdPath'];
      };
      cookie?: never;
    };
    get?: never;
    /**
     * Update secret
     * @description Requires write permission. Omit `value` to keep the stored value and change only metadata; description, rotation interval, expiry and metadata are replaced by the values sent.
     */
    put: operations['updateSecret'];
    post?: never;
    /**
     * Delete secret
     * @description Requires write permission. The secret is soft-deleted.
     */
    delete: operations['deleteSecret'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/secrets/{id}/reveal': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['SecretIdPath'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reveal secret value
     * @description Requires reveal permission (owner, admin or on-call). Every reveal is recorded in the audit log.
     */
    post: operations['revealSecret'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults/{id}/members': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
      };
      cookie?: never;
    };
    /**
     * List members
     * @description Explicit vault members. Requires read permission.
     */
    get: operations['listMembers'];
    put?: never;
    /**
     * Add member
     * @description Requires manage-members permission. The user must already belong to the vault's organization. Only owners can add another owner.
     */
    post: operations['addMember'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vaults/{id}/members/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
        userId: string;
      };
      cookie?: never;
    };
    get?: never;
    /**
     * Change member role
     * @description Requires manage-members permission. Only owners can grant or change the owner role, and the last owner cannot be demoted.
     */
    put: operations['updateMember'];
    post?: never;
    /**
     * Remove member
     * @description Requires manage-members permission. Callers cannot remove themselves, only owners can remove an owner, and the last owner cannot be removed.
     */
    delete: operations['removeMember'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/audit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Query the audit log
     * @description Newest first. Callers see their own events, every event in organizations they own or
     *     administer, and events in vaults where they are an owner or admin. snake_case aliases
     *     (`vault_id`, `user_id`, `org_id`, `environment_id`, `start_time`, `end_time`) are also accepted.
     */
    get: operations['listAuditEvents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Dashboard statistics
     * @description Counts across the vaults the caller can access.
     */
    get: operations['getStats'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/alerts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Dashboard alerts
     * @description Expired and soon-expiring (7 days) secrets and overdue rotations in accessible vaults, and members without a login in 90 days in vaults the caller manages. Ordered by severity, at most 50.
     */
    get: operations['listAlerts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      /**
       * @description Machine-readable code, e.g. not_found, forbidden, invalid_request
       * @example not_found
       */
      error: string;
      /** @example Vault not found */
      message: string;
    };
    MessageResponse: {
      message: string;
    };
    /** @enum {string} */
    Role: 'owner' | 'admin' | 'developer' | 'oncall' | 'viewer';
    RegisterRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
      name: string;
    };
    RegisterResponse: {
      /** Format: uuid */
      user_id: string;
      message: string;
    };
    VerifyEmailRequest: {
      token: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
    };
    RefreshRequest: {
      refresh_token: string;
    };
    AuthTokens: {
      access_token: string;
      refresh_token: string;
      /** @description Access token lifetime in seconds */
      expires_in: number;
    };
    ChangePasswordRequest: {
      /** Format: password */
      current_password: string;
      /** Format: password */
      new_password: string;
    };
    UserOrganization: {
      /** Format: uuid */
      id: string;
      name: string;
      role: components['schemas']['Role'];
    };
    UserProfile: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      name: string;
      /** Format: date-time */
      created_at: string;
      organizations: components['schemas']['UserOrganization'][];
    };
    Vault: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      organization_id: string;
      organization_name: string;
      name: string;
      description: string | null;
      user_role: components['schemas']['Role'];
      secret_count: number;
      env_count: number;
      /** Format: uuid */
      created_by_id: string | null;
      /** @description Creator's display name; empty when unknown */
      created_by: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    CreateVaultRequest: {
      name: string;
      description?: string | null;
      /** Format: uuid */
      organization_id?: string;
    };
    UpdateVaultRequest: {
      name: string;
      description?: string | null;
    };
    Environment: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      vault_id: string;
      name: string;
      description: string | null;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** @description Live secrets; only filled in by the list endpoint */
      secret_count: number;
    };
    EnvironmentRequest: {
      /** @example staging */
      name: string;
      description?: string | null;
    };
    RotationPolicy: {
      interval_days: number;
      /**
       * Format: date-time
       * @description When the value last changed; null if never since creation
       */
      last_rotated_at: string | null;
      /**
       * Format: date-time
       * @description One interval after the last rotation, or after creation
       */
      next_rotation_at: string;
    };
    SecretMetadata: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      environment_id: string;
      key_name: string;
      description?: string;
      rotation_interval_days?: number;
      /** Format: date-time */
      expires_at?: string;
      /** Format: date-time */
      last_rotated_at?: string;
      metadata?: {
        [key: string]: unknown;
      };
      /** Format: uuid */
      created_by: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: date-time */
      last_updated_at: string;
      /** Format: uuid */
      last_updated_by_id: string | null;
      /** @description Display name of the last editor */
      last_updated_by: string;
      rotation_policy: components['schemas']['RotationPolicy'] | null;
    };
    CreateSecretRequest: {
      key_name: string;
      /** Format: password */
      value: string;
      description?: string | null;
      rotation_interval_days?: number | null;
      /** Format: date-time */
      expires_at?: string | null;
      metadata?: {
        [key: string]: unknown;
      } | null;
    };
    UpdateSecretRequest: {
      /**
       * Format: password
       * @description New value; omit to keep the current one
       */
      value?: string;
      description?: string | null;
      rotation_interval_days?: number | null;
      /** Format: date-time */
      expires_at?: string | null;
      metadata?: {
        [key: string]: unknown;
      } | null;
    };
    SecretReveal: {
      /** Format: uuid */
      id: string;
      key_name: string;
      value: string;
      /** @description Seconds clients should show the value before hiding it */
      expires_in: number;
    };
    MemberPermissions: {
      can_read: boolean;
      can_write: boolean;
      can_reveal: boolean;
      can_manage_members: boolean;
      can_delete: boolean;
    };
    Member: {
      /** Format: uuid */
      user_id: string;
      /** Format: email */
      email: string;
      name: string;
      role: components['schemas']['Role'];
      permissions: components['schemas']['MemberPermissions'];
      /** Format: date-time */
      added_at: string;
      /** @description Display name of whoever added the member; empty when unknown */
      added_by: string;
      /** Format: uuid */
      added_by_id: string | null;
    };
    AddMemberRequest: {
      /** Format: email */
      email: string;
      role: components['schemas']['Role'];
    };
    UpdateMemberRequest: {
      role: components['schemas']['Role'];
    };
    /** @enum {string} */
    AuditAction:
      | 'login.success'
      | 'login.failure'
      | 'secret.created'
      | 'secret.updated'
      | 'secret.deleted'
      | 'secret.revealed'
      | 'member.added'
      | 'member.removed'
      | 'member.role_changed'
      | 'vault.created'
      | 'vault.updated'
      | 'vault.deleted'
      | 'env.created'
      | 'env.updated'
      | 'env.deleted';
    AuditEvent: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      timestamp: string;
      action: components['schemas']['AuditAction'];
      /** Format: uuid */
      user_id: string;
      /** Format: email */
      user_email: string;
      /** Format: uuid */
      organization_id: string | null;
      /** Format: uuid */
      vault_id: string | null;
      vault_name: string | null;
      /** Format: uuid */
      environment_id: string | null;
      environment_name: string | null;
      /** @description secret, environment, vault, member or user */
      target_type: string;
      /** Format: uuid */
      target_id: string | null;
      target_name: string | null;
      ip_address: string | null;
      user_agent: string | null;
      metadata: {
        [key: string]: unknown;
      };
    };
    AuditEventPage: {
      data: components['schemas']['AuditEvent'][];
      total: number;
      page: number;
      limit: number;
      has_more: boolean;
    };
    DashboardStats: {
      vaults: number;
      environments: number;
      secrets: number;
      secrets_expired: number;
      secrets_expiring_soon: number;
      secrets_rotation_overdue: number;
      /** @description People with access to the caller's vaults */
      users: number;
      /** @description Of those, how many logged in within active_window_days */
      active_users: number;
      expiring_soon_days: number;
      active_window_days: number;
    };
    DashboardAlert: {
      /** @enum {string} */
      type: 'secret_expired' | 'secret_expiring' | 'rotation_overdue' | 'member_inactive';
      /** @enum {string} */
      severity: 'high' | 'medium' | 'low';
      message: string;
      /** Format: uuid */
      vault_id: string;
      vault_name: string;
      environment_name: string | null;
      target_id: string;
      target_name: string;
      /**
       * Format: date-time
       * @description Expiry or rotation due date, or the member's last login (null if never)
       */
      due_at: string | null;
    };
    Health: {
      /** @enum {string} */
      status: 'ok' | 'unavailable';
      /** @example ok */
      database: string;
      migration_version: number | null;
      migration_dirty: boolean;
      /** Format: date-time */
      started_at: string;
      uptime_seconds: number;
      version: string;
      /** Format: date-time */
      timestamp: string;
    };
  };
  responses: {
    /** @description Unexpected server error (`internal_error`); details are logged, never returned */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Invalid ID, query parameter or body (`invalid_request`) */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Missing, invalid or expired access token */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description The caller's role does not allow this action (`forbidden`) */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Not found, or the caller has no access to it (`not_found`) */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description A resource with that name already exists (`duplicate` or `conflict`) */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: {
    VaultIdPath: string;
    EnvironmentIdPath: string;
    SecretIdPath: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Healthy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
      500: components['responses']['InternalError'];
      /** @description Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest'];
      };
    };
    responses: {
      /** @description Registered */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RegisterResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      /** @description An account with this email already exists (`user_already_exists`) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  verifyEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyEmailRequest'];
      };
    };
    responses: {
      /** @description Verified */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'];
        };
      };
      /** @description Missing, invalid, used or expired token (`invalid_verification`) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Logged in */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthTokens'];
        };
      };
      400: components['responses']['BadRequest'];
      /** @description Wrong email or password (`invalid_credentials`) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description Email not verified yet (`email_not_verified`) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  refreshTokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshRequest'];
      };
    };
    responses: {
      /** @description New tokens */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthTokens'];
        };
      };
      400: components['responses']['BadRequest'];
      /** @description Invalid, expired or revoked refresh token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshRequest'];
      };
    };
    responses: {
      /** @description Logged out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      /** @description Unknown refresh token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The authenticated user and their organizations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserProfile'];
        };
      };
      401: components['responses']['Unauthorized'];
      500: components['responses']['InternalError'];
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest'];
      };
    };
    responses: {
      /** @description Password changed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MessageResponse'];
        };
      };
      /** @description Missing fields, new password too short, or wrong current password */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      401: components['responses']['Unauthorized'];
      500: components['responses']['InternalError'];
    };
  };
  listVaults: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Vaults */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Vault'][];
        };
      };
      401: components['responses']['Unauthorized'];
      500: components['responses']['InternalError'];
    };
  };
  createVault: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateVaultRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Vault'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      409: components['responses']['Conflict'];
      500: components['responses']['InternalError'];
    };
  };
  getVault: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Vault */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Vault'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  updateVault: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateVaultRequest'];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Vault'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      500: components['responses']['InternalError'];
    };
  };
  deleteVault: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  listEnvironments: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        vault_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Environments */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Environment'][];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  createEnvironment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        vault_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EnvironmentRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Environment'];
        };
      };
      /** @description Invalid body or name (`invalid_name`) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      500: components['responses']['InternalError'];
    };
  };
  getEnvironment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Environment */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Environment'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  updateEnvironment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EnvironmentRequest'];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Environment'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      500: components['responses']['InternalError'];
    };
  };
  deleteEnvironment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  listSecrets: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Secrets */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SecretMetadata'][];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  createSecret: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['EnvironmentIdPath'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSecretRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SecretMetadata'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      500: components['responses']['InternalError'];
    };
  };
  updateSecret: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['SecretIdPath'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateSecretRequest'];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SecretMetadata'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  deleteSecret: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['SecretIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  revealSecret: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['SecretIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Decrypted value */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SecretReveal'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  listMembers: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Members */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Member'][];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  addMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddMemberRequest'];
      };
    };
    responses: {
      /** @description Added */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Member'];
        };
      };
      /** @description Invalid role or the user is not in the organization */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      /** @description Vault not found, or no user with that email */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      409: components['responses']['Conflict'];
      500: components['responses']['InternalError'];
    };
  };
  updateMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateMemberRequest'];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Member'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  removeMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['VaultIdPath'];
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalError'];
    };
  };
  listAuditEvents: {
    parameters: {
      query?: {
        page?: number;
        limit?: number;
        organizationId?: string;
        vaultId?: string;
        environmentId?: string;
        userId?: string;
        /** @description Case-insensitive substring of the actor's email */
        userEmail?: string;
        action?: components['schemas']['AuditAction'];
        /** @description Leave out events with this action; repeat for several */
        excludeAction?: components['schemas']['AuditAction'][];
        /** @description Inclusive; RFC 3339 timestamp or YYYY-MM-DD (UTC midnight) */
        startDate?: string;
        /** @description Exclusive for timestamps; a YYYY-MM-DD day includes that whole day */
        endDate?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description One page of events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuditEventPage'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      500: components['responses']['InternalError'];
    };
  };
  getStats: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Statistics */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DashboardStats'];
        };
      };
      401: components['responses']['Unauthorized'];
      500: components['responses']['InternalError'];
    };
  };
  listAlerts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Alerts */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DashboardAlert'][];
        };
      };
      401: components['responses']['Unauthorized'];
      500: components['responses']['InternalError'];
    };
  };
}
