#!/usr/bin/env bash
# Writes apps/api/.env for local development with freshly generated keys.
# An existing file is never overwritten.
set -euo pipefail

target="${1:-apps/api/.env}"
if [[ -f "$target" ]]; then
  echo "$target already exists; leaving it unchanged"
  exit 0
fi

random_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

umask 077
cat >"$target" <<ENV
# Local development only (gitignored). Generated by scripts/dev-env.sh.
MASTER_KEK=$(random_hex)
APP_JWT_SECRET=$(random_hex)
APP_DATABASE_HOST=${PGHOST:-localhost}
APP_DATABASE_PORT=${PGPORT:-5433}
APP_DATABASE_USER=${DB_USER:-secrets_user}
APP_DATABASE_PASSWORD=${DB_PASSWORD:-secrets_password}
APP_DATABASE_NAME=${DB_NAME:-secrets_db}
APP_DATABASE_SSLMODE=disable
APP_DATABASE_MIGRATIONS_PATH=./migrations
APP_SERVER_PORT=8080
ENV
echo "Wrote $target with new MASTER_KEK and APP_JWT_SECRET"
